## A very simple Neural Network


## One Input one Output

In [1]:
number_of_toes = [8.5, 9.5, 10, 9]
inputs = number_of_toes[0]
weight = 0.1
def neural_network(inputs,weight):
    prediction = inputs * weight
    return prediction
pred = neural_network(inputs, weight)



In [2]:
pred

0.8500000000000001

In [5]:
##%%time

def wtg_sum(a,b):
    assert(len(a) == len(b))
    output = 0
    for i in range(len(a)):
        
        output += a[i] * b[i]
    return output
weight = [0.1, 0.2, 0]

def neural_network(inputs, weight):
    pred = wtg_sum(inputs, weight)
    return pred
toes =  [8.5, 9.5, 9.9, 9.0]
wlrec = [0.65, 0.8, 0.8, 0.9]
nfans = [1.2, 1.3, 0.5, 1.0] 

inputs = [toes[0],wlrec[0],nfans[0]]
pred = neural_network(inputs,weight)

print(pred)



0.9800000000000001


## This is what is happening in the first part of the block of code above

In [11]:
a = [1,3,5,7]
b = [1,2,3,4]
assert(len(a) == len(b))

output = 0
for i in range(len(a)):
    output += (a[i] * b[i])
    print(output)

1
7
22
50


In [20]:
a = [1,3,5,7]
b = [1,2,3,4]
assert(len(a) == len(b))

output = 0
for i in range(len(a)):
    print(a[i],b[i])

1 1
3 2
5 3
7 4


## Using Numpy

In [12]:
%%time

import numpy as np
weight = np.array([0.1,0.2,0])
def Neural_network(inputs, weights):
    pred = np.dot(inputs, weights)
    return pred

toes =  np.array([8.5, 9.5, 9.9, 9.0])
wlrec = np.array([0.65, 0.8, 0.8, 0.9])
nfans = np.array([1.2, 1.3, 0.5, 1.0])

inputs = np.array([toes[0],wlrec[0],nfans[0]])
pred = neural_network(inputs, weight)
print(pred)

0.9800000000000001
Wall time: 4.15 s


`numpy` seems to be slower

In [7]:
type(neural_network)

function

## Building Neural Network from a single input with multiple output

In [14]:
def sig_mul(sig_input,vector):
    output = [0,0,0]
    assert(len(output) == len(vector))
    for i in range(len(vector)):
        output[i] = sig_input * vector[i]
    return output

weights = [0.3, 0.2, 0.9]
def neural_network(inputs, weights):
    pred = sig_mul(inputs,weights)
    return pred


wlrec = [0.65, 0.8, 0.8, 0.9]
input = wlrec[0]
pred = neural_network(input,weights)

print(pred)    

[0.195, 0.13, 0.5850000000000001]


## Numpy Version

In [73]:
import numpy as np
weight = np.array([0.3, 0.2, 0.9])
def Neural_network(inputs, weights):
    pred = np.dot(inputs, weights)
    return pred

toes =  np.array([8.5, 9.5, 9.9, 9.0])
wlrec = np.array([0.65, 0.8, 0.8, 0.9])
nfans = np.array([1.2, 1.3, 0.5, 1.0])

inputs = wlrec[0]
pred = Neural_network(inputs, weight)
print(pred)

[0.195 0.13  0.585]


## Predicting with multiple inputs & Output

In [38]:
weights = [[0.1, 0.1, -0.3],
           [0.1, 0.2, 0.0], 
           [0.0, 1.3, 0.1]]

def w_sum(a,b):
    assert(len(a) == len(b))
    output = 0
    for i in range(len(a)):
        output += (a[i] * b[i])
    return output

def vect_mat_mul(vect,matrix):
    assert(len(vect) == len(matrix))
    output = [0,0,0]
    for i in range(len(vect)):
        output[i] = w_sum(vect, matrix[i])
    return output
def neural_network(input, weights):
    pred = vect_mat_mul(input,weights)
    return pred


toes =  [8.5, 9.5, 9.9, 9.0]
wlrec = [0.65,0.8, 0.8, 0.9]
nfans = [1.2, 1.3, 0.5, 1.0]


input = [toes[0],wlrec[0],nfans[0]]
pred = neural_network(input,weights)

print(pred)

[0.555, 0.9800000000000001, 0.9650000000000001]


##  Numpy Version 

In [33]:
weights = np.array([[0.1, 0.1, -0.3],
           [0.1, 0.2, 0.0], 
           [0.0, 1.3, 0.1]])
inputs = np.array([8.5, 0.65, 1.2])


def mul_in_out(inputs, weights):
    result = inputs * weights
    pred = np.sum(result, axis = 1)
    return pred
mul_in_out(inputs, weights)

array([0.555, 0.98 , 0.965])

## Predicting on Prediction

In [39]:
ih_wgh = [[0.1, 0.2, -0.1],
         [-0.1, 0.1, 0.9],
         [0.1, 0.4, 0.1]]
hp_wgt = [[0.3, 1.1, -0.3],
         [0.1,0.2,0.0],
         [0.0, 1.3, 0.1]]

weights = [ih_wgh, hp_wgt]

def neural_network(inputs, weights):
    hid = vect_mat_mul(inputs, weights[0])
    pred = vect_mat_mul(hid,weights[1])
    return pred 


toes = [8.5, 9.5, 9.9, 9.0]
wlrec = [0.65, 0.8, 0.8, 0.9]
nfans = [1.2, 1.3, 0.5, 1.0]

inputs = [toes[0], wlrec[0], nfans[0]]
pred = neural_network(inputs, weights)

print(pred)

[0.21350000000000002, 0.14500000000000002, 0.5065]


## NumPy Version

In [57]:
import numpy as np
ih_wgh = np.array([[0.1, 0.2, -0.1],
         [-0.1, 0.1, 0.9],
         [0.1, 0.4, 0.1]]).T

hp_wgt = np.array([[0.3, 1.1, -0.3],
         [0.1,0.2,0.0],
         [0.0, 1.3, 0.1]]).T

weights = [ih_wgh, hp_wgt]

def neural_network(inputs, weights):
    hid = np.dot(inputs,weights[0])
    pred = np.dot(hid, weights[1])
    return pred


toes = np.array([8.5, 9.5, 9.9, 9.0])
wlrec = np.array([0.65, 0.8, 0.8, 0.9])
nfans = np.array([1.2, 1.3, 0.5, 1.0])

inputs = np.array([toes[0], wlrec[0], nfans[0]])
pred = neural_network(inputs, weights)

print(pred)

[0.2135 0.145  0.5065]
