In [2]:
def w_sum(a,b):
    assert(len(a) == len(b))
    output = 0
    
    for i in range(len(a)):
        output += (a[i] * b[i]) # performs weight input * operation
                                # That is weight * input
    return output

weight = [0.1,0.2, -0.1]


def neural_network(inputs, weight):
    pred = w_sum(inputs, weight) # w_sum operation on our neural network
    
    return pred

toes =  [8.5, 9.5, 9.9, 9.0]
wlrec = [0.65, 0.8, 0.8, 0.9]
nfans = [1.2, 1.3, 0.5, 1.0]

inputs = [toes[0],wlrec[0],nfans[0]] # correspond to the first enry for toe, wlrec, nfans
win_or_loss_binary = [1, 1, 0, 0]

true = win_or_loss_binary[0]

pred = neural_network(inputs, weight)
error = (pred - true) ** 2
delta = pred - true

def ele_mul(number, vector):
    output = [0,0,0]
    
    assert(len(output) == len(vector))
    
    for i in range(len(vector)):
        
        output[i] = number * vector[i]
        
    return output

alpha = 0.01

weight_delta = ele_mul(delta,weight)
for i in range(len(weight)): # updating each weight by multiplying with alpha alpha
    weight[i] -= (alpha * weight_delta[i])

print("Weights:" + str(weight))
print("Weight Deltas:" + str(weight_delta))

Weights:[0.10014, 0.20028, -0.10014]
Weight Deltas:[-0.013999999999999992, -0.027999999999999983, 0.013999999999999992]


In [3]:
def neural_network(inputs, weight):
    out = 0
    for i in range(len(inputs)):
        out += (input[i] * weight[i])
    return out

def ele_mul(scalar, vector):
    out = [0,0,0]
    for i in range(len(out)):
        out[i] = vector[i] * scalar
    return out

toes =  [8.5, 9.5, 9.9, 9.0]
wlrec = [0.65, 0.8, 0.8, 0.9]
nfans = [1.2, 1.3, 0.5, 1.0]


win_or_loss_binary = [1,1,0,0]
true = win_or_loss_binary[0]

alpha = 0.01

weight = [0.1, 0.2, -.1]
input = [toes[0],wlrec[0],nfans[0]]

for iter in range(3):
    pred = neural_network(inputs, weight)
    
    error = (pred - true) ** 2
    delta = pred - true
    
    weight_delta = ele_mul(delta, inputs)
    
    
    print("Iteration:" + str(iter+1))
    print("Pred:" + str(pred))
    print("Error:" + str(error))
    print("Delta:" + str(delta))
    print("weights:" + str(weight))
    print(str(weight_delta))
    print("------- "*7)
    
    
    for i in range(len(weight)):
        weight[i] -= alpha *weight_delta[i]
        

Iteration:1
Pred:0.8600000000000001
Error:0.01959999999999997
Delta:-0.1399999999999999
weights:[0.1, 0.2, -0.1]
[-1.189999999999999, -0.09099999999999994, -0.16799999999999987]
------- ------- ------- ------- ------- ------- ------- 
Iteration:2
Pred:0.9637574999999999
Error:0.0013135188062500048
Delta:-0.036242500000000066
weights:[0.1119, 0.20091, -0.09832]
[-0.30806125000000056, -0.023557625000000044, -0.04349100000000008]
------- ------- ------- ------- ------- ------- ------- 
Iteration:3
Pred:0.9906177228125002
Error:8.802712522307997e-05
Delta:-0.009382277187499843
weights:[0.11498061250000001, 0.20114557625, -0.09788509000000001]
[-0.07974935609374867, -0.006098480171874899, -0.011258732624999811]
------- ------- ------- ------- ------- ------- ------- 


## Let not update the weight the first weight and take note of the changes

In [4]:
def neural_network(inputs, weight):
    out = 0
    for i in range(len(inputs)):
        out += (input[i] * weight[i])
    return out

def ele_mul(scalar, vector):
    out = [0,0,0]
    for i in range(len(out)):
        out[i] = vector[i] * scalar
    return out

toes =  [8.5, 9.5, 9.9, 9.0]
wlrec = [0.65, 0.8, 0.8, 0.9]
nfans = [1.2, 1.3, 0.5, 1.0]


win_or_loss_binary = [1,1,0,0]
true = win_or_loss_binary[0]

alpha = 0.01

weight = [0.1, 0.2, -.1]
input = [toes[0],wlrec[0],nfans[0]]

for iter in range(3):
    pred = neural_network(inputs, weight)
    
    error = (pred - true) ** 2
    delta = pred - true
    
    weight_delta = ele_mul(delta, inputs)
    weight_delta[0] = 0
    
    
    print("Iteration:" + str(iter+1))
    print("Pred:" + str(pred))
    print("Error:" + str(error))
    print("Delta:" + str(delta))
    print("weights:" + str(weight))
    print(str(weight_delta))
    print("------- "*7)
    
    
    for i in range(len(weight)):
        weight[i] -= alpha *weight_delta[i]
        

Iteration:1
Pred:0.8600000000000001
Error:0.01959999999999997
Delta:-0.1399999999999999
weights:[0.1, 0.2, -0.1]
[0, -0.09099999999999994, -0.16799999999999987]
------- ------- ------- ------- ------- ------- ------- 
Iteration:2
Pred:0.8626075000000001
Error:0.018876699056249977
Delta:-0.13739249999999992
weights:[0.1, 0.20091, -0.09832]
[0, -0.08930512499999994, -0.1648709999999999]
------- ------- ------- ------- ------- ------- ------- 
Iteration:3
Pred:0.8651664353125001
Error:0.018180090166338207
Delta:-0.13483356468749985
weights:[0.1, 0.20180305125, -0.09667129]
[0, -0.0876418170468749, -0.16180027762499982]
------- ------- ------- ------- ------- ------- ------- 


## Let try same for weight[1]

In [5]:
def neural_network(inputs, weight):
    out = 0
    for i in range(len(inputs)):
        out += (input[i] * weight[i])
    return out

def ele_mul(scalar, vector):
    out = [0,0,0]
    for i in range(len(out)):
        out[i] = vector[i] * scalar
    return out

toes =  [8.5, 9.5, 9.9, 9.0]
wlrec = [0.65, 0.8, 0.8, 0.9]
nfans = [1.2, 1.3, 0.5, 1.0]


win_or_loss_binary = [1,1,0,0]
true = win_or_loss_binary[0]

alpha = 0.01

weight = [0.1, 0.2, -.1]
input = [toes[0],wlrec[0],nfans[0]]

for iter in range(3):
    pred = neural_network(inputs, weight)
    
    error = (pred - true) ** 2
    delta = pred - true
    
    weight_delta = ele_mul(delta, inputs)
    weight_delta[1] = 0
    
    
    print("Iteration:" + str(iter+1))
    print("Pred:" + str(pred))
    print("Error:" + str(error))
    print("Delta:" + str(delta))
    print("weights:" + str(weight))
    print(str(weight_delta))
    print("------- "*7)
    
    
    for i in range(len(weight)):
        weight[i] -= alpha *weight_delta[i]
        

Iteration:1
Pred:0.8600000000000001
Error:0.01959999999999997
Delta:-0.1399999999999999
weights:[0.1, 0.2, -0.1]
[-1.189999999999999, 0, -0.16799999999999987]
------- ------- ------- ------- ------- ------- ------- 
Iteration:2
Pred:0.9631660000000001
Error:0.0013567435559999942
Delta:-0.03683399999999992
weights:[0.1119, 0.2, -0.09832]
[-0.31308899999999934, 0, -0.04420079999999991]
------- ------- ------- ------- ------- ------- ------- 
Iteration:3
Pred:0.9903089745999998
Error:9.391597330344942e-05
Delta:-0.00969102540000022
weights:[0.11503089, 0.2, -0.09787799200000001]
[-0.08237371590000186, 0, -0.011629230480000263]
------- ------- ------- ------- ------- ------- ------- 


## Gradient descent with single input multiple output

In [6]:
weights = [0.3, 0.2, 0.9]

def neural_network(input, weights):
    pred = ele_mul(input, weights)
    return pred

wlrec = [0.65, 1.0, 1.0, 0.9]

hurt  = [0.1, 0.0, 0.0, 0.1]
win   = [  1,   1,   0,   1]
sad   = [0.1, 0.0, 0.1, 0.2]

input = wlrec[0]

pred = neural_network(input, weights)


true = [hurt[0], win[0], sad[0]]

pred = neural_network(input, weights)

error = [0, 0, 0]
delta = [0, 0, 0]

for i in range(len(true)):
    error[i] = (pred[i] - true[i]) ** 2
    delta[i] = pred[i] - true[i]
    
def scalar_neural(number, vector):
    output = [0, 0, 0]
    
    assert(len(output) == len(vector))
    
    for i in range(len(vector)):
        output[i] = number * vector[i]
        
    return output 

weight_delta  = scalar_neural(input, delta)

alpha = 0.1

for i in range(len(weight)):
    
    weights[i] -= (weight_delta[i] * alpha)
    
print("Weight:" + str(weights))
print("Weight Delta:" + str(weight_delta))

Weight:[0.293825, 0.25655, 0.868475]
Weight Delta:[0.061750000000000006, -0.5655, 0.3152500000000001]


## Gradient Descent with Multiple Inputs and Outputs

In [7]:
weights =[ [0.1, 0.1, -0.3],
         [0.1, 0.2, 0.0],
         [0.0, 1.3, 0.1]]
# this section takes care of input and weights multiplication
def w_sum(a,b):
    assert(len(a) == len(b))
    output = 0
    
    for i in range(len(a)):
        output += (a[i] * b[i])
    return output

def vect_mat_mul(vect, matrix):
    assert(len(vect) == len(matrix))
    output = [0, 0, 0]
    
    for i in range(len(vect)):
        output[i] = w_sum(vect, matrix[i])
    return output
    
def neural_network(inputs, weights):
    pred = vect_mat_mul(inputs, weights)
    return pred

toes  = [8.5, 9.5, 9.9, 9.0]
wlrec = [0.65,0.8, 0.8, 0.9]
nfans = [1.2, 1.3, 0.5, 1.0]

hurt  = [0.1, 0.0, 0.0, 0.1]
win   = [  1,   1,   0,   1]
sad   = [0.1, 0.0, 0.1, 0.2]

alpha = 0.01

input = [toes[0],wlrec[0],nfans[0]]
true  = [hurt[0], win[0], sad[0]]

pred = neural_network(inputs, weights)

error = [0, 0, 0] 
delta = [0, 0, 0]

for i in range(len(true)):
    error[i] = (pred[i] - true[i]) ** 2
    delta[i] = pred[i] - true[i]

In [8]:
import numpy as np

def outer_pred(a, b):
    
    out = np.zeros((len(a), len(b)))
    
    for i in range(len(a)):
        for j in range(len(b)):
            out[i][j] = a[i] * b[j]
    return out

weight_delta = outer_pred(delta, inputs)

for i in range(len(weights)):
    for j in range(len(weights[0])):
        weights[i][j] -= alpha * weight_delta[i][j]

In [9]:
weights

[[0.061325, 0.0970425, -0.30546],
 [0.1017, 0.20013, 0.00023999999999999887],
 [-0.07352500000000001, 1.2943775, 0.08962]]

In [24]:
import numpy as np

a = [1,3, 4]
b = [0, 2, 0]


out = np.zeros((len(a),len(b)))

for i in range(len(a)):
    for j in range(len(b)):
        out[i][j] = a[i] * b[j]
print(out)
       



[[0. 2. 0.]
 [0. 6. 0.]
 [0. 8. 0.]]
